const PHP = require('../../php')
const DB = require('../../database')
const config = require('../../config')

const commonLib = require('../lib/common.lib')
const installFunction = require('./install.function')
const installInc = require('./install.inc')

async function run(req, res, data = {}) {
  let returnData = {}

  let gmnow = PHP.gmdate() + ' GMT'
  res.set('Expires', 0) // rfc2616 - Section 14.21
  res.set('Last-Modified', gmnow)
  res.set('Cache-Control','no-store, no-cache, must-revalidate') // HTTP/1.1
  res.set('Cache-Control','pre-check=0, post-check=0, max-age=0') // HTTP/1.1
  res.set('Pragma','no-cache') // HTTP/1.0
  res.set('Content-Type','text/html; charset=utf-8')
  res.set('X-Robots-Tag','noindex')

  let title = config.G5_VERSION + ' 설치 완료 3/3'
  returnData.data_installInc = installInc({title})

  let mysql_host = installFunction.safe_install_string_check(req.body.mysql_host)
  let mysql_user = installFunction.safe_install_string_check(req.body.mysql_user)
  let mysql_pass = installFunction.safe_install_string_check(req.body.mysql_pass)
  let mysql_db = installFunction.safe_install_string_check(req.body.mysql_db)
  let table_prefix = installFunction.safe_install_string_check(req.body.table_prefix)
  let admin_id = req.body.admin_id
  let admin_pass = req.body.admin_pass
  let admin_name = req.body.admin_name
  let admin_email = req.body.admin_email

  if (/[^0-9a-z_]+/i.test(admin_id)) {
    returnData._status = 'UnsafeAdminID'
    return returnData
  }

  let dblink = DB.create(mysql_host, mysql_user, mysql_pass, mysql_db)
  try {
    await DB.connectionTest(dblink)
  } catch(err) {
    returnData._status = 'MySQLError'
    return returnData
  }
  /*
  let mysql_set_mode = false
  commonLib.sql_set_charset(config.G5_DB_CHARSET, dblink)

  let result = await dblink.raw('select @@sql_mode as mode')
  */

  // 테이블 생성 ------------------------------------
  // 기존 sql파일에서 불러와서 하는 방식에서 스크립트에서 쿼리 실행하는 방식으로 변경
  dblink.transaction(async (trx) => {
    await dblink.schema.dropTableIfExists(table_prefix + 'auth')
    await dblink.schema.createTable(table_prefix + 'auth', (table) => {
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.string('au_menu', 20).notNullable().defaultTo('')
      table.specificType('au_auth', `set('r', 'w', 'd')`).notNullable().defaultTo('') // knex does not have set() type (or mysql function)
      table.primary(['mb_id', 'au_menu'])
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'board')
    await dblink.schema.createTable(table_prefix + 'board', (table) => {
      table.string('bo_table', 20).notNullable().defaultTo('').primary()
      table.string('gr_id', 255).notNullable().defaultTo('')
      table.string('bo_subject', 255).notNullable().defaultTo('')
      table.string('bo_mobile_subject', 255).notNullable().defaultTo('')
      table.enu('bo_device', ['both', 'pc', 'mobile']).notNullable().defaultTo('both')
      table.string('bo_admin', 255).notNullable().defaultTo('')
      table.specificType('bo_list_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_read_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_write_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_reply_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_comment_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_upload_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_download_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_html_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_link_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_count_delete', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_count_modify', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('bo_read_point').notNullable().defaultTo(0)
      table.integer('bo_write_point').notNullable().defaultTo(0)
      table.integer('bo_comment_point').notNullable().defaultTo(0)
      table.integer('bo_download_point').notNullable().defaultTo(0)
      table.specificType('bo_use_category', 'tinyint(4)').notNullable().defaultTo(0)
      table.text('bo_category_list').notNullable()
      table.specificType('bo_use_sideview', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_file_content', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_secret', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_dhtml_editor', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_rss_view', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_good', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_nogood', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_name', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_signature', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_ip_view', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_list_view', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_list_file', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_list_content', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('bo_table_width').notNullable().defaultTo(0)
      table.integer('bo_subject_len').notNullable().defaultTo(0)
      table.integer('bo_mobile_subject_len').notNullable().defaultTo(0)
      table.integer('bo_page_rows').notNullable().defaultTo(0)
      table.integer('bo_mobile_page_rows').notNullable().defaultTo(0)
      table.integer('bo_new').notNullable().defaultTo(0)
      table.integer('bo_hot').notNullable().defaultTo(0)
      table.integer('bo_image_width').notNullable().defaultTo(0)
      table.string('bo_skin', 255).notNullable().defaultTo('')
      table.string('bo_mobile_skin', 255).notNullable().defaultTo('')
      table.string('bo_include_head', 255).notNullable().defaultTo('')
      table.string('bo_include_tail', 255).notNullable().defaultTo('')
      table.text('bo_content_head').notNullable()
      table.text('bo_mobile_content_head').notNullable()
      table.text('bo_content_tail').notNullable()
      table.text('bo_mobile_content_tail').notNullable()
      table.text('bo_insert_content').notNullable()
      table.integer('bo_gallery_cols').notNullable().defaultTo(0)
      table.integer('bo_gallery_width').notNullable().defaultTo(0)
      table.integer('bo_gallery_height').notNullable().defaultTo(0)
      table.integer('bo_mobile_gallery_width').notNullable().defaultTo(0)
      table.integer('bo_mobile_gallery_height').notNullable().defaultTo(0)
      table.integer('bo_upload_size').notNullable().defaultTo(0)
      table.specificType('bo_reply_order', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_search', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('bo_order').notNullable().defaultTo(0)
      table.integer('bo_count_write').notNullable().defaultTo(0)
      table.integer('bo_count_comment').notNullable().defaultTo(0)
      table.integer('bo_write_min').notNullable().defaultTo(0)
      table.integer('bo_write_max').notNullable().defaultTo(0)
      table.integer('bo_comment_min').notNullable().defaultTo(0)
      table.integer('bo_comment_max').notNullable().defaultTo(0)
      table.text('bo_notice').notNullable()
      table.specificType('bo_upload_count', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_email', 'tinyint(4)').notNullable().defaultTo(0)
      table.enu('bo_use_cert', ['', 'cert', 'adult', 'hp-cert', 'hp-adult']).notNullable().defaultTo('')
      table.specificType('bo_use_sns', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('bo_use_captcha', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('bo_soft_field', 255).notNullable().defaultTo('')
      table.string('bo_1_subj', 255).notNullable().defaultTo('')
      table.string('bo_2_subj', 255).notNullable().defaultTo('')
      table.string('bo_3_subj', 255).notNullable().defaultTo('')
      table.string('bo_4_subj', 255).notNullable().defaultTo('')
      table.string('bo_5_subj', 255).notNullable().defaultTo('')
      table.string('bo_6_subj', 255).notNullable().defaultTo('')
      table.string('bo_7_subj', 255).notNullable().defaultTo('')
      table.string('bo_8_subj', 255).notNullable().defaultTo('')
      table.string('bo_9_subj', 255).notNullable().defaultTo('')
      table.string('bo_10_subj', 255).notNullable().defaultTo('')
      table.string('bo_1', 255).notNullable().defaultTo('')
      table.string('bo_2', 255).notNullable().defaultTo('')
      table.string('bo_3', 255).notNullable().defaultTo('')
      table.string('bo_4', 255).notNullable().defaultTo('')
      table.string('bo_5', 255).notNullable().defaultTo('')
      table.string('bo_6', 255).notNullable().defaultTo('')
      table.string('bo_7', 255).notNullable().defaultTo('')
      table.string('bo_8', 255).notNullable().defaultTo('')
      table.string('bo_9', 255).notNullable().defaultTo('')
      table.string('bo_10', 255).notNullable().defaultTo('')

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'board_file')
    await dblink.schema.createTable(table_prefix + 'board_file', (table) => {
      table.string('bo_table', 20).notNullable().defaultTo('')
      table.integer('wr_id').notNullable().defaultTo(0)
      table.integer('bf_no').notNullable().defaultTo(0)
      table.string('bf_source', 255).notNullable().defaultTo('')
      table.string('bf_file', 255).notNullable().defaultTo('')
      table.integer('bf_download').notNullable()
      table.text('bf_content').notNullable()
      table.string('bf_fileurl', 255).notNullable().defaultTo('')
      table.string('bf_thumburl', 255).notNullable().defaultTo('')
      table.string('bf_storage', 50).notNullable().defaultTo('')
      table.integer('bf_filesize').notNullable().defaultTo(0)
      table.integer('bf_width').notNullable().defaultTo(0)
      table.specificType('bf_height', 'smallint(6)').notNullable().defaultTo(0)
      table.specificType('bf_type', 'tinyint(4)').notNullable().defaultTo(0)
      table.datetime('bf_datetime').notNullable().defaultTo('0000-00-00 00:00:00')

      table.primary(['bo_table', 'wr_id', 'bf_no'])
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'board_good')
    await dblink.schema.createTable(table_prefix + 'board_good', (table) => {
      table.increments('bg_id').notNullable().primary()
      table.string('bo_table', 20).notNullable().defaultTo('')
      table.integer('wr_id').notNullable().defaultTo(0)
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.string('bg_flag', 255).notNullable().defaultTo('')
      table.datetime('bg_datetime').notNullable().defaultTo('0000-00-00 00:00:00')

      table.unique(['bo_table', 'wr_id', 'mb_id'], 'fkey1')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'board_new')
    await dblink.schema.createTable(table_prefix + 'board_new', (table) => {
      table.increments('bn_id').notNullable().primary()
      table.string('bo_table', 20).notNullable().defaultTo('')
      table.integer('wr_id').notNullable().defaultTo(0)
      table.integer('wr_parent').notNullable().defaultTo(0)
      table.datetime('bn_datetime').notNullable().defaultTo('0000-00-00 00:00:00')
      table.string('mb_id', 20).notNullable().defaultTo('')

      table.index('mb_id', 'mb_id')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'config')
    await dblink.schema.createTable(table_prefix + 'config', (table) => {
      table.string('cf_title', 255).notNullable().defaultTo('')
      table.string('cf_theme', 100).notNullable().defaultTo('')
      table.string('cf_admin', 100).notNullable().defaultTo('')
      table.string('cf_admin_email', 100).notNullable().defaultTo('')
      table.string('cf_admin_email_name', 100).notNullable().defaultTo('')
      table.text('cf_add_script').notNullable()
      table.specificType('cf_use_point', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('cf_point_term').notNullable().defaultTo(0)
      table.specificType('cf_use_copy_log', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_use_email_certify', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('cf_login_point').notNullable().defaultTo(0)
      table.specificType('cf_cut_name', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('cf_nick_modify').notNullable().defaultTo(0)
      table.string('cf_new_skin', 50).notNullable().defaultTo('')
      table.integer('cf_new_rows').notNullable().defaultTo(0)
      table.string('cf_search_skin', 50).notNullable().defaultTo('')
      table.string('cf_connect_skin', 50).notNullable().defaultTo('')
      table.string('cf_faq_skin', 50).notNullable().defaultTo('')
      table.integer('cf_read_point').notNullable().defaultTo(0)
      table.integer('cf_write_point').notNullable().defaultTo(0)
      table.integer('cf_comment_point').notNullable().defaultTo(0)
      table.integer('cf_download_point').notNullable().defaultTo(0)
      table.integer('cf_write_pages').notNullable().defaultTo(0)
      table.integer('cf_mobile_pages').notNullable().defaultTo(0)
      table.string('cf_link_target', 50).notNullable().defaultTo('')
      table.specificType('cf_bbs_rewrite','tinyint(4)').notNullable().defaultTo(0)
      table.integer('cf_delay_sec').notNullable().defaultTo(0)
      table.text('cf_filter').notNullable()
      table.text('cf_possible_ip').notNullable()
      table.text('cf_intercept_ip').notNullable()
      table.text('cf_analytics').notNullable()
      table.text('cf_add_meta').notNullable()
      table.string('cf_member_skin', 50).notNullable().defaultTo('')
      table.specificType('cf_use_homepage', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_req_homepage', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_use_tel', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_req_tel', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_use_hp', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_req_hp', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_use_addr', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_req_addr', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_use_signature', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_req_signature', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_use_profile', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_req_profile', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_register_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('cf_register_point').notNullable().defaultTo(0)
      table.specificType('cf_icon_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_use_recommend', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('cf_recommend_point').notNullable().defaultTo(0)
      table.integer('cf_leave_day').notNullable().defaultTo(0)
      table.integer('cg_search_part').notNullable().defaultTo(0)
      table.specificType('cf_email_use', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_email_wr_super_admin', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_email_wr_group_admin', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_email_wr_board_admin', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_email_wr_write', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_email_wr_comment_all', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_email_mb_super_admin', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_email_mb_member', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('cf_email_po_super_admin', 'tinyint(4)').notNullable().defaultTo(0)
      table.text('cf_prohibit_id').notNullable()
      table.text('cf_prohibit_email').notNullable()
      table.integer('cf_new_del').notNullable().defaultTo(0)
      table.integer('cf_memo_del').notNullable().defaultTo(0)
      table.integer('cf_visit_del').notNullable().defaultTo(0)
      table.integer('cf_popular_del').notNullable().defaultTo(0)
      table.date('cf_optimize_date').notNullable().defaultTo('0000-00-00')
      table.specificType('cf_use_member_icon', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('cf_member_icon_size').notNullable().defaultTo(0)
      table.integer('cf_member_icon_width').notNullable().defaultTo(0)
      table.integer('cf_member_icon_height').notNullable().defaultTo(0)
      table.integer('cf_member_img_size').notNullable().defaultTo(0)
      table.integer('cf_member_img_width').notNullable().defaultTo(0)
      table.integer('cf_member_img_height').notNullable().defaultTo(0)
      table.integer('cf_login_minutes').notNullable().defaultTo(0)
      table.string('cf_image_extension', 255).notNullable().defaultTo('')
      table.string('cf_flash_extension', 255).notNullable().defaultTo('')
      table.string('cf_movie_extension', 255).notNullable().defaultTo('')
      table.specificType('cf_formmail_is_member', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('cf_page_rows').notNullable().defaultTo(0)
      table.integer('cf_mobile_page_rows').notNullable().defaultTo(0)
      table.string('cf_visit', 255).notNullable().defaultTo('')
      table.integer('cf_max_po_id').notNullable().defaultTo(0)
      table.text('cf_stipulation').notNullable()
      table.text('cf_privacy').notNullable()
      table.integer('cf_open_modify').notNullable().defaultTo(0)
      table.integer('cf_memo_send_point').notNullable().defaultTo(0)
      table.string('cf_mobile_new_skin', 50).notNullable().defaultTo('')
      table.string('cf_mobile_search_skin', 50).notNullable().defaultTo('')
      table.string('cf_mobile_connect_skin', 50).notNullable().defaultTo('')
      table.string('cf_mobile_faq_skin', 50).notNullable().defaultTo('')
      table.string('cf_mobile_member_skin', 50).notNullable().defaultTo('')
      table.string('cf_captcha_mp3', 255).notNullable().defaultTo('')
      table.string('cf_editor', 50).notNullable().defaultTo('')
      table.specificType('cf_cert_use', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('cf_cert_ipin', 255).notNullable().defaultTo('')
      table.string('cf_cert_hp', 255).notNullable().defaultTo('')
      table.string('cf_cert_kcb_cd', 255).notNullable().defaultTo('')
      table.string('cf_cert_kcp_cd', 255).notNullable().defaultTo('')
      table.string('cf_lg_mid', 100).notNullable().defaultTo('')
      table.string('cf_lg_mert_key', 100).notNullable().defaultTo('')
      table.integer('cf_cert_limit').notNullable().defaultTo(0)
      table.specificType('cf_cert_req', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('cf_sms_use', 255).notNullable().defaultTo('')
      table.string('cf_sms_type', 10).notNullable().defaultTo('')
      table.string('cf_icode_id', 255).notNullable().defaultTo('')
      table.string('cf_icode_pw', 255).notNullable().defaultTo('')
      table.string('cf_icode_server_ip', 50).notNullable().defaultTo('')
      table.string('cf_icode_server_port', 50).notNullable().defaultTo('')
      table.string('cf_googl_shorturl_apikey', 50).notNullable().defaultTo('')
      table.specificType('cf_social_login_use', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('cf_social_servicelist', 255).notNullable().defaultTo('')
      table.string('cf_payco_clientid', 100).notNullable().defaultTo('')
      table.string('cf_payco_secret', 100).notNullable().defaultTo('')
      table.string('cf_facebook_appid', 100).notNullable()
      table.string('cf_facebook_secret', 100).notNullable()
      table.string('cf_twitter_key', 100).notNullable()
      table.string('cf_twitter_secret', 100).notNullable()
      table.string('cf_google_clientid', 100).notNullable().defaultTo('')
      table.string('cf_google_secret', 100).notNullable().defaultTo('')
      table.string('cf_naver_clientid', 100).notNullable().defaultTo('')
      table.string('cf_naver_secret', 100).notNullable().defaultTo('')
      table.string('cf_kakao_rest_key', 100).notNullable().defaultTo('')
      table.string('cf_kakao_client_secret', 100).notNullable().defaultTo('')
      table.string('cf_kakao_js_apikey', 100).notNullable().defaultTo('')
      table.string('cf_captcha', 100).notNullable().defaultTo('')
      table.string('cf_recaptcha_site_key', 100).notNullable().defaultTo('')
      table.string('cf_recaptcha_secret_key', 100).notNullable().defaultTo('')
      table.string('cf_1_subj', 255).notNullable().defaultTo('')
      table.string('cf_2_subj', 255).notNullable().defaultTo('')
      table.string('cf_3_subj', 255).notNullable().defaultTo('')
      table.string('cf_4_subj', 255).notNullable().defaultTo('')
      table.string('cf_5_subj', 255).notNullable().defaultTo('')
      table.string('cf_6_subj', 255).notNullable().defaultTo('')
      table.string('cf_7_subj', 255).notNullable().defaultTo('')
      table.string('cf_8_subj', 255).notNullable().defaultTo('')
      table.string('cf_9_subj', 255).notNullable().defaultTo('')
      table.string('cf_10_subj', 255).notNullable().defaultTo('')
      table.string('cf_1', 255).notNullable().defaultTo('')
      table.string('cf_2', 255).notNullable().defaultTo('')
      table.string('cf_3', 255).notNullable().defaultTo('')
      table.string('cf_4', 255).notNullable().defaultTo('')
      table.string('cf_5', 255).notNullable().defaultTo('')
      table.string('cf_6', 255).notNullable().defaultTo('')
      table.string('cf_7', 255).notNullable().defaultTo('')
      table.string('cf_8', 255).notNullable().defaultTo('')
      table.string('cf_9', 255).notNullable().defaultTo('')
      table.string('cf_10', 255).notNullable().defaultTo('')

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'cert_history')
    await dblink.schema.createTable(table_prefix + 'cert_history', (table) => {
      table.increments('cr_id').notNullable().primary()
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.string('cr_company', 255).notNullable().defaultTo('')
      table.string('cr_method', 255).notNullable().defaultTo('')
      table.string('cr_ip', 255).notNullable().defaultTo('')
      table.date('cr_date').notNullable().defaultTo('0000-00-00')
      table.time('cr_time').notNullable().defaultTo('00:00:00')

      table.index('mb_id', 'mb_id')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'group')
    await dblink.schema.createTable(table_prefix + 'group', (table) => {
      table.string('gr_id', 10).notNullable().defaultTo('').primary()
      table.string('gr_subject', 255).notNullable().defaultTo('')
      table.enu('gr_device', ['both', 'pc', 'mobile']).notNullable().defaultTo('both')
      table.string('gr_admin', 255).notNullable().defaultTo('')
      table.specificType('gr_use_access', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('gr_order').notNullable().defaultTo(0)
      table.string('gr_1_subj', 255).notNullable().defaultTo('')
      table.string('gr_2_subj', 255).notNullable().defaultTo('')
      table.string('gr_3_subj', 255).notNullable().defaultTo('')
      table.string('gr_4_subj', 255).notNullable().defaultTo('')
      table.string('gr_5_subj', 255).notNullable().defaultTo('')
      table.string('gr_6_subj', 255).notNullable().defaultTo('')
      table.string('gr_7_subj', 255).notNullable().defaultTo('')
      table.string('gr_8_subj', 255).notNullable().defaultTo('')
      table.string('gr_9_subj', 255).notNullable().defaultTo('')
      table.string('gr_10_subj', 255).notNullable().defaultTo('')
      table.string('gr_1', 255).notNullable().defaultTo('')
      table.string('gr_2', 255).notNullable().defaultTo('')
      table.string('gr_3', 255).notNullable().defaultTo('')
      table.string('gr_4', 255).notNullable().defaultTo('')
      table.string('gr_5', 255).notNullable().defaultTo('')
      table.string('gr_6', 255).notNullable().defaultTo('')
      table.string('gr_7', 255).notNullable().defaultTo('')
      table.string('gr_8', 255).notNullable().defaultTo('')
      table.string('gr_9', 255).notNullable().defaultTo('')
      table.string('gr_10', 255).notNullable().defaultTo('')

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'group_member')
    await dblink.schema.createTable(table_prefix + 'group_member', (table) => {
      table.increments('gm_id').notNullable().primary()
      table.string('gr_id', 255).notNullable().defaultTo('')
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.datetime('gm_datetime').notNullable().defaultTo('0000-00-00 00:00:00')

      table.index('gr_id', 'gr_id')
      table.index('mb_id', 'mb_id')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'login')
    await dblink.schema.createTable(table_prefix + 'login', (table) => {
      table.string('lo_ip', 100).notNullable().defaultTo('').primary()
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.datetime('lo_datetime').notNullable().defaultTo('0000-00-00 00:00:00')
      table.text('lo_location').notNullable()
      table.text('lo_url').notNullable()

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'mail')
    await dblink.schema.createTable(table_prefix + 'mail', (table) => {
      table.increments('ma_id').notNullable().primary()
      table.string('ma_subject', 255).notNullable().defaultTo('')
      table.text('ma_content', 'mediumtext').notNullable()
      table.datetime('ma_time').notNullable().defaultTo('0000-00-00 00:00:00')
      table.string('ma_ip', 255).notNullable().defaultTo('')
      table.text('ma_last_option').notNullable()

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'member')
    await dblink.schema.createTable(table_prefix + 'member', (table) => {
      table.increments('mb_no').notNullable().primary()
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.string('mb_password', 255).notNullable().defaultTo('')
      table.string('mb_name', 255).notNullable().defaultTo('')
      table.string('mb_nick', 255).notNullable().defaultTo('')
      table.date('mb_nick_date').notNullable().defaultTo('0000-00-00')
      table.string('mb_email', 255).notNullable().defaultTo('')
      table.string('mb_homepage', 255).notNullable().defaultTo('')
      table.specificType('mb_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('mb_sex', 'char(1)').notNullable().defaultTo('')
      table.string('mb_birth', 255).notNullable().defaultTo('')
      table.string('mb_tel', 255).notNullable().defaultTo('')
      table.string('mb_hp', 255).notNullable().defaultTo('')
      table.string('mb_certify', 20).notNullable().defaultTo('')
      table.specificType('mb_adult', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('mb_dupinfo', 255).notNullable().defaultTo('')
      table.specificType('mb_zip1', 'char(3)').notNullable().defaultTo('')
      table.specificType('mb_zip2', 'char(3)').notNullable().defaultTo('')
      table.string('mb_addr1', 255).notNullable().defaultTo('')
      table.string('mb_addr2', 255).notNullable().defaultTo('')
      table.string('mb_addr3', 255).notNullable().defaultTo('')
      table.string('mb_addr_jibeon', 255).notNullable().defaultTo('')
      table.text('mb_signature').notNullable()
      table.string('mb_recommend', 255).notNullable().defaultTo('')
      table.integer('mb_point').notNullable().defaultTo(0)
      table.datetime('mb_today_login').notNullable().defaultTo('0000-00-00 00:00:00')
      table.string('mb_login_ip', 255).notNullable().defaultTo('')
      table.datetime('mb_datetime').notNullable().defaultTo('0000-00-00 00:00:00')
      table.string('mb_ip', 255).notNullable().defaultTo('')
      table.string('mb_leave_date', 8).notNullable().defaultTo('')
      table.string('mb_intercept_date', 8).notNullable().defaultTo('')
      table.datetime('mb_email_certify').notNullable().defaultTo('0000-00-00 00:00:00')
      table.string('mb_email_certify2', 255).notNullable().defaultTo('')
      table.text('mb_memo').notNullable()
      table.string('mb_lost_certify', 255).notNullable().defaultTo('')
      table.specificType('mb_mailling', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('mb_sms', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('mb_open', 'tinyint(4)').notNullable().defaultTo(0)
      table.date('mb_open_date').notNullable().defaultTo('0000-00-00')
      table.text('mb_profile').notNullable()
      table.string('mb_memo_call', 255).notNullable().defaultTo('')
      table.integer('mb_memo_cnt').notNullable().defaultTo(0)
      table.integer('mb_scrap_cnt').notNullable().defaultTo(0)
      table.string('mb_1', 255).notNullable().defaultTo('')
      table.string('mb_2', 255).notNullable().defaultTo('')
      table.string('mb_3', 255).notNullable().defaultTo('')
      table.string('mb_4', 255).notNullable().defaultTo('')
      table.string('mb_5', 255).notNullable().defaultTo('')
      table.string('mb_6', 255).notNullable().defaultTo('')
      table.string('mb_7', 255).notNullable().defaultTo('')
      table.string('mb_8', 255).notNullable().defaultTo('')
      table.string('mb_9', 255).notNullable().defaultTo('')
      table.string('mb_10', 255).notNullable().defaultTo('')

      table.unique('mb_id', 'mb_id')
      table.index('mb_today_login', 'mb_today_login')
      table.index('mb_datetime', 'mb_datetime')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'memo')
    await dblink.schema.createTable(table_prefix + 'memo', (table) => {
      table.increments('me_id').notNullable().primary()
      table.string('me_recv_mb_id', 20).notNullable().defaultTo('')
      table.string('me_send_mb_id', 20).notNullable().defaultTo('')
      table.datetime('me_send_datetime').notNullable().defaultTo('0000-00-00 00:00:00')
      table.datetime('me_read_datetime').notNullable().defaultTo('0000-00-00 00:00:00')
      table.text('me_memo').notNullable()
      table.integer('me_send_id').notNullable().defaultTo(0)
      table.enu('me_type', ['send', 'recv']).notNullable().defaultTo('recv')
      table.string('me_send_ip', 100).notNullable().defaultTo('')

      table.index('me_recv_mb_id', 'me_recv_mb_id')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'point')
    await dblink.schema.createTable(table_prefix + 'point', (table) => {
      table.integer('po_id').notNullable().primary()
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.datetime('po_datetime').notNullable().defaultTo('0000-00-00 00:00:00')
      table.string('po_content', 255).notNullable().defaultTo('')
      table.integer('po_point').notNullable().defaultTo(0)
      table.integer('po_use_point').notNullable().defaultTo(0)
      table.specificType('po_expired', 'tinyint(4)').notNullable().defaultTo(0)
      table.date('po_expire_date').notNullable().defaultTo('0000-00-00')
      table.integer('po_mb_point').notNullable().defaultTo(0)
      table.string('po_rel_table', 20).notNullable().defaultTo('')
      table.string('po_rel_id', 20).notNullable().defaultTo('')
      table.string('po_rel_action', 100).notNullable().defaultTo('')

      table.index(['mb_id', 'po_rel_table', 'po_rel_id', 'po_rel_action'], 'index1')
      table.index('po_expire_date', 'index2')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'poll')
    await dblink.schema.createTable(table_prefix + 'poll', (table) => {
      table.increments('po_id').notNullable().primary()
      table.string('po_subject', 255).notNullable().defaultTo('')
      table.string('po_poll1', 255).notNullable().defaultTo('')
      table.string('po_poll2', 255).notNullable().defaultTo('')
      table.string('po_poll3', 255).notNullable().defaultTo('')
      table.string('po_poll4', 255).notNullable().defaultTo('')
      table.string('po_poll5', 255).notNullable().defaultTo('')
      table.string('po_poll6', 255).notNullable().defaultTo('')
      table.string('po_poll7', 255).notNullable().defaultTo('')
      table.string('po_poll8', 255).notNullable().defaultTo('')
      table.string('po_poll9', 255).notNullable().defaultTo('')
      table.integer('po_cnt1').notNullable().defaultTo(0)
      table.integer('po_cnt2').notNullable().defaultTo(0)
      table.integer('po_cnt3').notNullable().defaultTo(0)
      table.integer('po_cnt4').notNullable().defaultTo(0)
      table.integer('po_cnt5').notNullable().defaultTo(0)
      table.integer('po_cnt6').notNullable().defaultTo(0)
      table.integer('po_cnt7').notNullable().defaultTo(0)
      table.integer('po_cnt8').notNullable().defaultTo(0)
      table.integer('po_cnt9').notNullable().defaultTo(0)
      table.string('po_etc', 255).notNullable().defaultTo('')
      table.specificType('po_level', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('po_point').notNullable().defaultTo(0)
      table.date('po_date').notNullable().defaultTo('0000-00-00')
      table.text('po_ips', 'mediumtext').notNullable()
      table.text('mb_ids').notNullable()

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'poll_etc')
    await dblink.schema.createTable(table_prefix + 'poll_etc', (table) => {
      table.integer('pc_id').notNullable().defaultTo(0).primary()
      table.integer('po_id').notNullable().defaultTo(0)
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.string('pc_name', 255).notNullable().defaultTo('')
      table.string('pc_idea', 255).notNullable().defaultTo('')
      table.datetime('pc_datetime').notNullable().defaultTo('0000-00-00 00:00:00')

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'popular')
    await dblink.schema.createTable(table_prefix + 'popular', (table) => {
      table.increments('pp_id').notNullable().primary()
      table.string('pp_word', 50).notNullable().defaultTo('')
      table.date('pp_date').notNullable().defaultTo('0000-00-00')
      table.string('pp_ip', 50).notNullable().defaultTo('')

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'scrap')
    await dblink.schema.createTable(table_prefix + 'scrap', (table) => {
      table.increments('ms_id').notNullable().primary()
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.string('bo_table', 20).notNullable().defaultTo('')
      table.string('wr_id', 15).notNullable().defaultTo('')
      table.datetime('ms_datetime').notNullable().defaultTo('0000-00-00 00:00:00')

      table.index('mb_id', 'mb_id')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    dblink.schema.dropTableIfExists(table_prefix + 'visit')
    dblink.schema.createTable(table_prefix + 'visit', (table) => {
      table.integer('vi_id').notNullable().defaultTo(0).primary()
      table.string('vi_ip', 100).notNullable().defaultTo('')
      table.date('vi_date').notNullable().defaultTo('0000-00-00')
      table.time('vi_time').notNullable().defaultTo('00:00:00')
      table.text('vi_referer').notNullable()
      table.string('vi_agent', 200).notNullable().defaultTo('')
      table.string('vi_browser', 255).notNullable().defaultTo('')
      table.string('vi_os', 255).notNullable().defaultTo('')
      table.string('vi_device', 255).notNullable().defaultTo('')

      table.unique(['vi_ip', 'vi_date'], 'index1')
      table.index('vi_date', 'index2')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'visit_sum')
    await dblink.schema.createTable(table_prefix + 'visit_sum', (table) => {
      table.date('vs_date').notNullable().defaultTo('0000-00-00').primary()
      table.integer('vs_count').notNullable().defaultTo(0)

      table.index('vs_count', 'index1')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'uniqid')
    await dblink.schema.createTable(table_prefix + 'uniqid', (table) => {
      table.bigInteger('uq_id').unsigned().notNullable().primary()
      table.string('uq_ip', 255).notNullable()

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'autosave')
    await dblink.schema.createTable(table_prefix + 'autosave', (table) => {
      table.increments('as_id').notNullable().primary()
      table.string('mb_id', 20).notNullable()
      table.bigInteger('as_uid').notNullable()
      table.string('as_subject', 255).notNullable()
      table.text('as_content').notNullable()
      table.datetime('as_datetime').notNullable()

      table.unique('as_uid', 'as_uid')
      table.index('mb_id', 'mb_id')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'qa_config')
    await dblink.schema.createTable(table_prefix + 'qa_config', (table) => {
      table.string('qa_title', 255).notNullable().defaultTo('')
      table.string('qa_category', 255).notNullable().defaultTo('')
      table.string('qa_skin', 255).notNullable().defaultTo('')
      table.string('qa_mobile_skin', 255).notNullable().defaultTo('')
      table.specificType('qa_use_email', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('qa_req_email', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('qa_use_hp', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('qa_req_hp', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('qa_use_sms', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('qa_send_number', 255).notNullable().defaultTo('0')
      table.string('qa_admin_hp', 255).notNullable().defaultTo('')
      table.string('qa_admin_email', 255).notNullable().defaultTo('')
      table.specificType('qa_use_editor', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('qa_subject_len').notNullable().defaultTo(0)
      table.integer('qa_mobile_subject_len').notNullable().defaultTo(0)
      table.integer('qa_page_rows').notNullable().defaultTo(0)
      table.integer('qa_mobile_page_rows').notNullable().defaultTo(0)
      table.integer('qa_image_width').notNullable().defaultTo(0)
      table.integer('qa_upload_size').notNullable().defaultTo(0)
      table.text('qa_insert_content').notNullable()
      table.string('qa_include_head', 255).notNullable().defaultTo('')
      table.string('qa_include_tail', 255).notNullable().defaultTo('')
      table.text('qa_content_head').notNullable()
      table.text('qa_content_tail').notNullable()
      table.text('qa_mobile_content_head').notNullable()
      table.text('qa_mobile_content_tail').notNullable()
      table.string('qa_1_subj', 255).notNullable().defaultTo('')
      table.string('qa_2_subj', 255).notNullable().defaultTo('')
      table.string('qa_3_subj', 255).notNullable().defaultTo('')
      table.string('qa_4_subj', 255).notNullable().defaultTo('')
      table.string('qa_5_subj', 255).notNullable().defaultTo('')
      table.string('qa_1', 255).notNullable().defaultTo('')
      table.string('qa_2', 255).notNullable().defaultTo('')
      table.string('qa_3', 255).notNullable().defaultTo('')
      table.string('qa_4', 255).notNullable().defaultTo('')
      table.string('qa_5', 255).notNullable().defaultTo('')

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'qa_content')
    await dblink.schema.createTable(table_prefix + 'qa_content', (table) => {
      table.increments('qa_id').notNullable().primary()
      table.integer('qa_num').notNullable().defaultTo(0)
      table.integer('qa_parent').notNullable().defaultTo(0)
      table.integer('qa_related').notNullable().defaultTo(0)
      table.string('mb_id', 20).notNullable().defaultTo('')
      table.string('qa_name', 255).notNullable().defaultTo('')
      table.string('qa_email', 255).notNullable().defaultTo('')
      table.string('qa_hp', 255).notNullable().defaultTo('')
      table.specificType('qa_type', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('qa_category', 255).notNullable().defaultTo('')
      table.specificType('qa_email_recv', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('qa_sms_recv', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('qa_html', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('qa_subject', 255).notNullable().defaultTo('')
      table.text('qa_content').notNullable()
      table.specificType('qa_status', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('qa_file1', 255).notNullable().defaultTo('')
      table.string('qa_source1', 255).notNullable().defaultTo('')
      table.string('qa_file2', 255).notNullable().defaultTo('')
      table.string('qa_source2', 255).notNullable().defaultTo('')
      table.string('qa_ip', 255).notNullable().defaultTo('')
      table.datetime('qa_datetime').notNullable().defaultTo('0000-00-00 00:00:00')
      table.string('qa_1', 255).notNullable().defaultTo('')
      table.string('qa_2', 255).notNullable().defaultTo('')
      table.string('qa_3', 255).notNullable().defaultTo('')
      table.string('qa_4', 255).notNullable().defaultTo('')
      table.string('qa_5', 255).notNullable().defaultTo('')

      table.index(['qa_num', 'qa_parent'], 'qa_num_parent')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'content')
    await dblink.schema.createTable(table_prefix + 'content', (table) => {
      table.string('co_id', 20).notNullable().defaultTo('')
      table.specificType('co_html', 'tinyint(4)').notNullable().defaultTo(0)
      table.string('co_subject', 255).notNullable().defaultTo('')
      table.text('co_content', 'longtext').notNullable()
      table.string('co_seo_title', 255).notNullable().defaultTo('')
      table.text('co_mobile_content', 'longtext').notNullable()
      table.string('co_skin', 255).notNullable().defaultTo('')
      table.string('co_mobile_skin', 255).notNullable().defaultTo('')
      table.specificType('co_tag_filter_use', 'tinyint(4)').notNullable().defaultTo(0)
      table.integer('co_hit').notNullable().defaultTo(0)
      table.string('co_include_head', 255).notNullable().defaultTo('')
      table.string('co_include_tail', 255).notNullable().defaultTo('')

      table.index('co_seo_title', 'co_seo_title')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'faq')
    await dblink.schema.createTable(table_prefix + 'faq', (table) => {
      table.increments('fa_id').notNullable().primary()
      table.integer('fm_id').notNullable().defaultTo(0)
      table.text('fa_subject').notNullable()
      table.text('fa_content').notNullable()
      table.integer('fa_order').notNullable().defaultTo(0)

      table.index('fm_id', 'fm_id')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'faq_master')
    await dblink.schema.createTable(table_prefix + 'faq_master', (table) => {
      table.increments('fm_id').notNullable().primary()
      table.string('fm_subject', 255).notNullable().defaultTo('')
      table.text('fm_head_html').notNullable()
      table.text('fm_tail_html').notNullable()
      table.text('fm_mobile_head_html').notNullable()
      table.text('fm_mobile_tail_html').notNullable()
      table.integer('fm_order').notNullable().defaultTo(0)

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'member_social_profiles')
    await dblink.schema.createTable(table_prefix + 'member_social_profiles', (table) => {
      table.increments('mp_no').notNullable()
      table.string('mb_id', 255).notNullable().defaultTo('')
      table.string('provider', 50).notNullable().defaultTo('')
      table.string('object_sha', 45).notNullable().defaultTo('')
      table.string('identifier', 255).notNullable().defaultTo('')
      table.string('profileurl', 255).notNullable().defaultTo('')
      table.string('photourl', 255).notNullable().defaultTo('')
      table.string('displayname', 150).notNullable().defaultTo('')
      table.string('description', 255).notNullable().defaultTo('')
      table.datetime('mp_register_day').notNullable().defaultTo('0000-00-00 00:00:00')
      table.datetime('mp_latest_day').notNullable().defaultTo('0000-00-00 00:00:00')

      table.unique('mp_no', 'mp_no')
      table.index('mb_id', 'mb_id')
      table.index('provider', 'provider')
      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'new_win')
    await dblink.schema.createTable(table_prefix + 'new_win', (table) => {
      table.increments('nw_id').notNullable().primary()
      table.string('nw_device', 10).notNullable().defaultTo('')
      table.datetime('nw_begin_time').notNullable().defaultTo('0000-00-00 00:00:00')
      table.datetime('nw_end_time').notNullable().defaultTo('0000-00-00 00:00:00')
      table.integer('nw_disable_hours').notNullable().defaultTo(0)
      table.integer('nw_left').notNullable().defaultTo(0)
      table.integer('nw_top').notNullable().defaultTo(0)
      table.integer('nw_height').notNullable().defaultTo(0)
      table.integer('nw_width').notNullable().defaultTo(0)
      table.text('nw_subject').notNullable()
      table.text('nw_content').notNullable()
      table.specificType('nw_content_html').notNullable().defaultTo(0)

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await dblink.schema.dropTableIfExists(table_prefix + 'menu')
    await dblink.schema.createTable(table_prefix + 'menu', (table) => {
      table.increments('me_id').notNullable().primary()
      table.string('me_code', 255).notNullable().defaultTo('')
      table.string('me_name', 255).notNullable().defaultTo('')
      table.string('me_link', 255).notNullable().defaultTo('')
      table.string('me_target', 255).notNullable().defaultTo('')
      table.integer('me_order').notNullable().defaultTo(0)
      table.specificType('me_use', 'tinyint(4)').notNullable().defaultTo(0)
      table.specificType('me_mobile_use', 'tinyint(4)').nnotNullable().defaultTo(0)

      table.engine('MyISAM')
      table.charset('utf8')
    })

    await trx.commit()
    // TODO catch() => show error message
  })

  returnData._status = 'OK'
  return returnData
}

module.exports = run
